# Generated by Django 2.2.2 on 2019-07-08 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_movieimagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieImageModel',
            new_name='MovieImage',
        ),
    ]
